<html>
    <head>
        <title>Server Error</title>
        <link rel="shortcut icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABNUlEQVQ4jZ3Tv0pcQRQG8N8Ml2CV6tYiEmwMksInMD6AjY9grAbyp0wZxC4Wt9H4CGnyALL4DEEsLMQi5TSBIBbL3hQ7K3cvdxX3g4HhfN/5zuGcmaCHtm7WcIBdrJXwHUY4DznddvWhk1jhGz7jVd+4YIzv+BpyGj8alOSf2OuIHzCrto6VDvcL+yGncSyBo14y3IScNkNOm7jpcXs4htjWzZvS9kvxsa2bjYhDVEsYVDiIptNeFrvRdEDLYj0+r3kSsTJ9JFtDZFs3r2f3BQZ3FS4XGLzF32c6GEWcYTJA3uN9Of8G+AnOY8jpGqcDgquQ0yjkNML1AH8acrqa7f8LNsyvdLutm+NSabvfesmZ+0wrOMEHi4c2wQ98Cjk9zBl0jN6ZfucdrJbwH1zgLOT0u6v/D0mmTb6gKDocAAAAAElFTkSuQmCC" />
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
        <style>
            body{background:linear-gradient(90deg,#ed578b 0,#ed576a 100%)}.wrapper{font-family:'Segoe UI',sans-serif;display:flex;align-items:center;justify-content:center;width:100%;height:100%}.wrapper h1{font-weight:300;color:#fff;font-size:24px;}
        </style>
    </head>
    <body>
        <div class="wrapper">
            <h1>500 | Server Error</h1>
        </div>
    </body>
</html>