<html>
    <head>
        <title>Server Error</title>
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
        <style>
            body{
                display: flex;
                align-items: center;
                justify-content: center;
                width: 100vw;
                height: 100vh;
            }
        </style>
    </head>
    <body>
        <h1>Server Error</h1>
    </body>
</html>