<html lang="en">

<head>
    <meta charset="UTF-8">
    <title><?= $title ?? ''; ?></title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <meta name="color-scheme" content="dark white">
    <style>
        <?= \Glowie\Core\Error\Handler::getAsset('default.css') ?>
    </style>
</head>

<body>
    <div class="wrapper">
        <h1><?= $title ?? ''; ?></h1>
    </div>
</body>

</html>