<!--
<?= var_dump(...$vars); ?>
-->
<html>

<head>
    <title>Variable dump</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <meta name="color-scheme" content="dark white">
    <style>
        <?= self::getAsset('dump.css'); ?>
    </style>
</head>

<body>
    <div class="wrapper">
        <?php foreach ($vars as $var): ?>
            <div class="title">
                <strong>Variable dump of type:</strong> <?= is_object($var) ? get_class($var) : gettype($var); ?>
            </div>
            <div class="details">
                <pre><?= self::parseDump($var) ?></pre>
            </div>
        <?php endforeach; ?>
        <div class="title">
            <span>Glowie <?= self::getVersion(); ?> | PHP <?= phpversion(); ?></span>
        </div>
    </div>
    <script>
        <?= self::getAsset('script.js'); ?>
    </script>
</body>

</html>
<!--
<?= var_dump(...$vars); ?>
-->